### ISSUE TITLE
Const step size (4kB) != (1 << 10). (1 << 10) == 1024

### ISSUE THREAD

**Issue by victorshcherbakov** [CoffeeBeforeArch/spring_2020_tutorial#1]
https://github.com/CoffeeBeforeArch/spring_2020_tutorial/blob/376daf92c4c36c343c4dfa1df5a6108a59424b87/associativity/l1_bench.cpp#L12-L13

**Comment by CoffeeBeforeArch** [comment]
The step size is 1k elements in a vector of integers. Integers are 4B each leading to 1k integers times 4 bytes per integer which is 4kB.

**Comment by victorshcherbakov** [comment]
Thank you for explanation
